# Generated by Django 4.2.5 on 2023-09-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolveGia', '0002_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='amount_of_type_numbers',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TypeNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('spec_time', models.PositiveIntegerField(default=0)),
                ('tasks', models.ManyToManyField(related_name='typentotasks', to='SolveGia.task')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='type_numbers',
            field=models.ManyToManyField(to='SolveGia.typenumber'),
        ),
    ]
