# Generated by Django 4.2.5 on 2023-09-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolveGia', '0004_rename_try_attempt_remove_result_tries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='amount_of_type_numbers',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
