# Generated by Django 4.2.5 on 2023-09-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolveGia', '0005_alter_category_amount_of_type_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='median_rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
