# Generated by Django 4.2.5 on 2023-09-18 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SolveGia', '0007_alter_variant_median_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['pk', 'rating']},
        ),
    ]
