# Generated by Django 4.2.5 on 2023-09-22 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SolveGia', '0008_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='variant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='SolveGia.variant'),
            preserve_default=False,
        ),
    ]
