# Generated by Django 4.2.5 on 2023-09-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_customuser_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='failed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='solved',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
