# Generated by Django 4.2.5 on 2023-09-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='number',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
