# Generated by Django 4.2.5 on 2023-09-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_rename_number_status_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='in_groups',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
